alphagov/govuk-fastly

modules/www/www.vcl.tftpl
There was a statement missing the set the variable to enable selecting the backend when the "Backend-Override" header was set in staging.
=> Fix Backend-Override to use mirror in staging

modules/www/www.vcl.tftpl
As an outcome of RFC-163, we are trying to simplify our CDN configuration by removing functionality that’s no longer used, or by moving logic to other parts of the stack.
This change was suggested in a comment on RFC-163
(https://github.com/alphagov/govuk-rfcs/pull/163#discussion_r1289816022):
"I think the flag for Whitehall recommended links should be removed. It was put in as a safety mechanism for the introduction of the links, in case something really inappropriate was found. There are ways to manually override the links now, and we've never used the feature flag."
The application logic dependent on this header is removed in https://github.com/alphagov/government-frontend/pull/2918
It's now recommended to create feature flags as environment variables in helm charts.
[Trello …
=> Remove Govuk-Use-Recommended-Related-Links header

modules/bouncer/bouncer.vcl.tftpl, modules/www/www.vcl.tftpl
Remove VCL code as this logic is handled by AWS WAF
Trello: https://trello.com/c/tprMplI9/3293-move-logic-for-serving-an-http-404-if-request-url-matches-autodiscover-autodiscoverxml-from-cdn-to-waf-3
=> Remove autodiscover 404 logic

modules/www/www.vcl.tftpl
Temporarily allow requests for the homepage to retain query strings
A new design of the gov.uk homepage is being rolled out. To prevent a big bang release, and increase confidence, we intend to ship those changes piecemeal, hiding them behind a query string. 
Remove the logic originally added in https://github.com/alphagov/govuk-cdn-config/commit/37eacc22f418d579d3bf14b27eaca4ae6cc96d55. We assume that it was added to improve caching performance.
=> Temporarily allow requests for the homepage to retain query strings

modules/bouncer/bouncer.vcl.tftpl
See https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/working-at-gds/gds-internal-it/gds-internal-it-network-public-ip-addresses
=> Remove obsolete IP from the office IP range

modules/www/service.tf, modules/www/www.vcl.tftpl
[Trello card](https://trello.com/c/vr0xCoVR/3308-move-contact-form-honeypot-from-cdn-into-waf-5)
This functionality is no longer needed after merging alphagov/govuk-fastly-secrets#6 (more details are available in that PR's description)
=> Remove private_extra_vcl_recv

modules/www/www.vcl.tftpl
In staging we test the client IP to allow access only to office or VPN IPs. However when using shielding in Fastly, the client.ip variable may be set to a Fastly server. By using True-Client-IP instead, we conserve the IP of the original client.
=> Use req.http.True-Client-IP when testing for original client IP.

modules/www/www.vcl.tftpl
This change prevents Fastly from adding ".html" to the end of requests for ".woff" or ".woff2" font types.
=> Fix serving fonts via the mirror backends

modules/www/www.vcl.tftpl
This is enabled through setting a header to override the backend in which to retrieve content. This has been tested in Staging.
=> Enable accessing mirrored version of GOV.UK in prod

diff-generator/Dockerfile, diff-generator/requirements.txt
Tested: `docker build .` works locally.
=> Pin only to major versions to reduce Dependabot toil.

modules/bouncer/bouncer.vcl.tftpl
Update the ACL reflect the changes to [GDS Office and VPN Public IP Addresses](https://sites.google.com/a/digital.cabinet-office.gov.uk/gds/working-at-gds/gds-internal-it/gds-internal-it-network-public-ip-addresses) which came into effect on 1 Oct.
=> Update purge_ip_allowlist to reflect recent changes.

modules/assets/assets.vcl.tftpl, modules/bouncer/bouncer.vcl.tftpl, modules/www/www.vcl.tftpl
It's unused by Fastly and has been deprecated. For more information see https://developer.fastly.com/reference/http/http-headers/Fastly-Cachetype/
Trello card: https://trello.com/c/1oMeBT0O/3356-remove-deprecated-use-of-fastly-cachetype-header-2
=> Remove deprecated use of Fastly-Cachetype header

ab_tests.yaml, dictionaries.yaml
Trello: https://trello.com/c/XAPAI9sT/212-set-up-ab-test-for-new-search-on-govuk-platform
The new test will use the same Dimension (41) as the old Elastic search A/A control test.
=> Setup vertex search ab test

ab_tests.yaml, dictionaries.yaml
[Trello](https://trello.com/c/GJ5lt8ij/589-set-up-the-next-round-of-a-b-tests)
This PR adds temporary A/B Tests to 3 pages on government-frontend: 
- https://www.gov.uk/stop-being-self-employed
- https://www.gov.uk/pay-self-assessment-tax-bill/pay-weekly-monthly
- https://www.gov.uk/log-in-file-self-assessment-tax-return
=> CB/DT - Add AB Tests for SA videos

modules/www/service.tf
Probaby easier to review the two commits separately - the first one reformats the format string, the second one adds protocol.
There is a follow up PR in govuk-aws to have AWS glue parse this field for use in Athena - https://github.com/alphagov/govuk-aws/pull/1812
=> Add protocol to athena logs

modules/assets/service.tf, modules/www/service.tf
We've had this running in staging for the last couple of days, where we've done some testing both with local browsers and with Webpagetest.
This has given us reasonable confidence that this will:
a) Not break the website
b) Not make performance significantly worse
[a] - Because HTTP/3 is something that browsers will only upgrade to if they support it, there should be no effect on old browsers. We've tested staging with Firefox / Chrome / Safari / Edge and they all upgrade to HTTP/3 successfully and there aren't any observable issues with the site.
[b] - Synthetic testing hasn't shown the performance improvements were expecting, even for the high packet loss case where we were expecting the biggest performance gains. It doesn't look noticeably worse though, and there's only so far you can …
=> Enable HTTP/3 for www and assets in all envs

modules/assets/service.tf
I'd missed off the trailing V which Fastly wants in the format string. This was there in the www config, but not in the assets config. Consequently, we were getting the following error when applying terraform:
Error: invalid configuration for Fastly Service (...): Failed to parse log format string.
=> Fix format of logging string for assets

modules/assets/assets.vcl.tftpl
As part of the licensify migration we're updating the IPs for our NAT Gateways. The gateways in Staging have already been updated. Keeping the old IPs for production incase we need to revert during the migration. Will remove in subsequent PR.
=> Add IPs for new NAT Gateways

datagovuk.tf, modules/datagovuk/datagovuk.vcl.tftpl, modules/datagovuk/provider.tf, modules/datagovuk/service.tf, modules/datagovuk/variables.tf
Migrates data.gov.uk fastly services from [govuk-aws](https://github.com/alphagov/govuk-aws/tree/5359b86/terraform/projects/fastly-datagovuk) & [govuk-aws-data](https://github.com/alphagov/govuk-aws-data/tree/b65921e/data/fastly-datagovuk) and aligns it with the other services config. 
Changes to the original config and additions to the standard ones are included in the separate commits.
[Trello 1](https://trello.com/c/MeFx5HpA/3331-migrate-dgu-fastly-services-from-govuk-aws-to-govuk-fastly-5), [Trello 2](https://trello.com/c/U8BJLa3w/3269-get-the-fastly-cdn-logs-for-dgu-into-splunk-5)
- https://github.com/alphagov/govuk-fastly-secrets/pull/9
=> Add data.gov.uk

datagovuk.tf
This module is failing in fastly. It needs be removed so that other changes can still go ahead whilst it is being fixed.
=> Temporarily removes the datagovuk in integration

ab_tests.yaml, dictionaries.yaml
In preparation for Phase 2 of testing, this PR changes the names of the tests involved in phase 2, whilst also removing `sa_video_pay_bill` as its no longer being tested.
[Trello](https://trello.com/c/8n9KMaqo/611-video-a-b-tests-setup-phase-2-a-b-tests)
=> Change multiple variable names in preparation for phase 2 of testing

dictionaries.yaml
Temporarily turns off the VertexSearch A/B test.
We've found through testing that some important documents are being removed from the Google index, even though they are being updated in the datastore correctly.
Until this problem is fixed it's not safe to continue with the A/B test as some of the documents affected are for self-assessment and the self-assessment deadline is imminent.
=> Turn off VertexSearch A/B test

modules/datagovuk/datagovuk.vcl.tftpl
To match https://github.com/alphagov/govuk-fastly/blob/main/modules/datagovuk/datagovuk.vcl.tftpl#L1
DGU has only 1 backend. This was missed when updating the name.
=> Update default backend for DGU

modules/datagovuk/datagovuk.vcl.tftpl
Those are new directives added during a migration to TF Cloud however it requires access to values in
https://github.com/alphagov/govuk-fastly-secrets/blob/main/dictionaries.yaml and caused an error on apply: "Undefined `table ip_address_denylist`"
It can be added once the existing config has been successful ported.
=> Remove deny list logic from DGU

modules/datagovuk/service.tf
DGU only has 1 backend. The default backend in defined in [modules/datagovuk/datagovuk.vcl.tftpl](https://github.com/alphagov/govuk-fastly/blob/main/modules/datagovuk/datagovuk.vcl.tftpl#L1-L37)
=> Remove dynamic block for creating additional backends from DGU

dictionaries.yaml
We're happy that the problem of documents being removed from the new Google search index has been resolved [1], so the A/B test can continue as planned.
[1]: https://github.com/alphagov/govuk-fastly/pull/54
=> Ramp up VertexSearch to 50%

datagovuk.tf, modules/datagovuk/service.tf
We tested it in integration and staging so now rolling it out to production.
[Plan output](https://app.terraform.io/app/govuk/workspaces/govuk-fastly/runs/run-XqzZurCxTnaLmEJy)
- https://github.com/alphagov/govuk-fastly-secrets/pull/19
- headers
- response objects
=> Rollout data.gov.uk Fastly configuration to production

modules/www/www.vcl.tftpl
- This sets the HSTS header to the domain within VCL
- Enables consistency throughout the CDN.
Trello: https://trello.com/c/0TgCOgbX/3397-3-configure-fastly-to-always-append-an-hsts-header
=> Add HTTP Strict-Transport-Security header to unknown URLs

modules/assets/assets.vcl.tftpl, modules/bouncer/bouncer.vcl.tftpl, modules/www/www.vcl.tftpl
The following variables were deprecated:
- req-grace: https://www.fastly.com/documentation/reference/vcl/variables/server/req-grace/
- beresp.grace: https://www.fastly.com/documentation/reference/vcl/variables/backend-response/beresp-grace/
=> Update deprecated variables

modules/www/www.vcl.tftpl
We don't need to pass query parameters to origin for the homepage. This [used to be on govuk-cdn-config](https://github.com/alphagov/govuk-cdn-config/blob/main/vcl_templates/www.vcl.erb#L255C1-L258C4).
This change improves our ability to cache here, which is important as we get quite spiky traffic on occasion.
=> Ignore query parameters on the homepage

dictionaries.yaml
Some bits were missed when the VertexSearch was removed in: https://github.com/alphagov/govuk-fastly/pull/65
=> Clean up VertexSearch A/B test

datagovuk.tf
Missed that this needed to be repeated for each environment in 5017416.
=> Add missing dictionaries to datagovuk config.

modules/datagovuk/datagovuk.vcl.tftpl, modules/datagovuk/service.tf, modules/www/service.tf, modules/www/www.vcl.tftpl
We want to be able to temporarily alter request by adding private (stored in govuk-fastly-secrets) configuration to the subroutine. This may be helpful when handling with incidents.
https://trello.com/c/suUIHnnk/3483-allow-to-configure-private-extra-vclrecv-for-www-and-dgu
- https://github.com/alphagov/govuk-fastly-secrets/pull/23
=> Allow to configure private extra vcl_recv for www and DGU

modules/datagovuk/datagovuk.vcl.tftpl
This was removed in https://github.com/alphagov/govuk-fastly/pull/58 and can now be added back.
https://trello.com/c/Oiai95mm/3458-enable-ja3-fingerprinting-for-dgu-3
=> Enable JA3 fingerprinting for DGU

dictionaries.yaml
For 10 days 95% of users should see variant A and the rest should see variant B.
Trello card: https://trello.com/c/VUPBYG8Y
=> Ramp up new browse AB test

modules/service-domain-redirect/provider.tf, modules/service-domain-redirect/service.tf, modules/service-domain-redirect/servicegovuk.vcl, service_domain_redirect.tf
The VCL for this service was not migrated over to govuk-fastly. This PR creates the Production service domain redirect Service in Infrastructure as Code.
Trello: https://trello.com/c/r6PSkf8Q/3491-import-production-service-domain-redirect-fastly-service-to-terraform-5
=> Migrate servicegovuk

ab_tests.yaml, dictionaries.yaml
Remove NewBrowse A/B test so we have full 7 days at 50%. This is related to the following [PR](https://github.com/alphagov/collections/pull/3630).
So that we can analyse the results and do the work properly if we were to move to lists
[Trello card](https://trello.com/c/NcutO6EF/2615-remove-a-b-test-and-revert-list-pr-s-m)
I've confirmed in the Terraform diff that the changes introduced are as expected. The hash changes are discussed in this thread and they are confirmed to be harmless: https://gds.slack.com/archives/C013F737737/p1716550143651819?thread_ts=1716541278.025089&cid=C013F737737
=> Remove NewBrowse A/B test

modules/datagovuk/datagovuk.vcl.tftpl
Configure serving stale content on error status codes in DGU.
Fastly documentation: https://docs.fastly.com/en/guides/serving-stale-content
Trello: https://trello.com/c/717ASEtA/3544-fix-serving-stale-content-configuration-for-dgu-5
=> Handle errors and deliver stale content

modules/datagovuk/datagovuk.vcl.tftpl
The config didn't take effect, it seems like it could be due to the syntax as https://github.com/alphagov/govuk-fastly/blame/75cc8dc4516b40179df30bd14d3cb55b58f5faeb/modules/datagovuk/datagovuk.vcl.tftpl#L109 shows the correct way so a refactor has beeen done.
=> Update syntax to target integration

.github/workflows/build_diff_gen_image.yaml
This will push the image to ghcr.io instead of directly to ECR.
=> Use the reusable workflow for building images

modules/www/main.tf, modules/www/www.vcl.tftpl
Description:
- Static assets (such as CSS, images and Javascript) are stored in an S3 bucket. Currently to retrieve a static asset Fastly will make a request to an nginx pod running in router. nginx will then retrieve the static asset from S3 before passing it to Fastly.
- This commit makes Fastly talk directly to S3 without going through nginx and Router by are handled in the if block above which triggers a restart causing Fastly to poll the S3 mirror instead.
- If the static asset doesn't exist in S3 (e.g. [www.gov.uk/assets/non-existent.jpg](http://www.gov.uk/assets/non-existent.jpg)) then S3 returns an XML document and 403. Adding the condition to display a prettified error page for this would make the VCL code difficult to read as well as a special case to handle integration which …
=> Load static assets from S3 directly

modules/www/www.vcl.tftpl
Description:
- As part of https://github.com/alphagov/govuk-fastly/issues/73 Fastly now talks directly to S3 to serve up static assets
- However in the integration environment the `Authorization: Basic xxx` header is set which Fastly sends along to S3 causing S3 to incorrectly interpret it as an authorization request. This causes a 400 error to return for the static assets
- Following unsets the header so Fastly can correctly send a non-authorized GET request to S3 to retrieve the object and resolve this error
=> Fix static assets returning 400 error in integration

modules/assets/main.tf, modules/bouncer/main.tf, modules/datagovuk/main.tf, modules/www/main.tf
We introducted rate limiting at 500 req/s as a canary to ensure that we didn't effect anything. This lowers the rate limit to a threshold that's more protective.
=> Reduce rate limit to 100

.github/workflows/build_diff_gen_image.yaml
The diff generator lambda is trying to pull the `latest` image from the repository, but the standard build workflow only tags a newly built image with a hash.
=> Tag diff-generator image as latest after new image is built

.github/workflows/build_diff_gen_image.yaml
Image names are prefixed with `govuk/` which I missed in my original PR
=> Fix diff gen image URI in tag-latest job

.github/workflows/build_diff_gen_image.yaml
These permissions are required for the workflow to write to GHCR
=> Add required permissions to tag-latest step

chat.tf, modules/chat/chat.vcl.tftpl, modules/chat/main.tf, modules/chat/provider.tf, modules/chat/variables.tf, variables.tf
In normal operation Fastly will send traffic directly to the origin unless we set the disable_service variable to true, then it will return a 503 error.
=> Add new edge configuration for Chat.

dictionaries.yaml
[Trello](https://trello.com/c/q6KtBz1F/2782-ramp-up-popular-tasks-ab-test-10-to-a-b-and-c-for-2-days-preparation-only-do-not-merge-s)
Increased the AB test percentage's so that variants A, B, and C are seen by 10% of users respectively, while the remaining 70% see the Z variant.
Updated the cookie duration for the AB test to 2 days.
=> Ramp up popular tasks ab test 2 days

dictionaries.yaml
[Trello](https://trello.com/c/Lq1EG1pN/2781-ramp-up-popular-tasks-ab-test-33-to-a-and-33-b-and-33-c-and-1z-preparation-only-do-not-merge-s)
The AB test percentages have been updated so that 33% of users see Variant A, 33% see Variant B, 33% see Variant C, and 1% see Variant Z.
The cookie duration for the AB test has also been extended to 3 months.
=> Ramp up PopularTasks AB Test - 33% to A, B and C

modules/www/www.vcl.tftpl
Description:
- Previously non-standard/unimplemented HTTP requests such as `DEBUG` will pass through Fastly and hit the origin where nginx rejects them as 501. See [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) as to why this is the appropriate status code to return
- Here Fastly is configured to throw a 501 and return custom HTML. The error code `806` and not `805` is used as the latter is used by `_security_txt_response.vcl` in the [shared VCL](https://github.com/alphagov/govuk-fastly/blob/main/modules/shared/_security_txt_response.vcl)
- `FASTLYPURGE` is how the non-standard `PURGE` method appears in [VCL](https://www.fastly.com/documentation/reference/vcl/variables/client-request/req-method/)
- Tested in integration and staging:
```
curl -w …
```
=> Reject non-standard HTTP methods at edge

www/www.vcl.tftpl
Trello: https://trello.com/c/VZsfdz7x/1739-spike-into-configuring-govuk-infrastructure-so-that-we-can-serve-chat-on-wwwgovuk-chat
GOV.UK Chat is going to be hosted on www.gov.uk/chat and will make use of cookies. Therefore we are going to need to alter the VCL so that cookies are not automatically stripped.
For GOV.UK Chat we want the homepage (GET /chat) to be cached so the regex matches only apply to paths within /chat/*.
If a user has a session cookie for chat we want to always pass the message to the server, if they don't have this session cookie it will be safe to strip to cookies where there may.
I wasn't 100% sure about the behaviour of Fastly caching when cookies are set or not, so to avoid any accidental cachings I've set it to pass any responses received from /chat/* that set a …
=> Cookie handling for GOV.UK Chat

www/www.vcl.tftpl
I used the incorrect variable name where I should have been referencing backend response.
=> Correct s/resp/beresp/

mobile-backend/service.tf
This PR fixes up a couple of things in the mobile-backend integration service - namely:
* TTL doesn't need to be a header in its own right (and upsets creation of the service)
* We need to set the `override_host` value in order to point at the correct S3 bucket (per guidance [here](https://docs.fastly.com/en/guides/amazon-s3#:~:text=In%20the-,Override%20host,-field%2C%20enter%20an))
* SSL for some reason was not enabled by default, so setting the `use_ssl` param
=> fixup mobile backend int service to point at s3 correctly

www/service.tf, www/www.vcl.tftpl
In case of an emergency we want a way to disable the service at the edge.
=> Add a disable_chat bool to disable the GOV.UK chat service

dictionaries.yaml, www/ab_tests.yaml
We will shortly be testing a new autocomplete component for site search.
This sets up the AB test with an initial 0/0/100 split (all baseline/"Z"), to allow us to get the rest of the AB test plumbing into place and use it as a mini feature flag to start testing the functionality on production.
=> Add `SearchAutocomplete` AB test

www/www.vcl.tftpl
GOV.UK Chat makes use of one-time magic links. These magic links are vulnerable to mail clients sending a HEAD request. Our application code can then reject the HEAD request.
However a problem is that Fastly will convert these HEAD requests into GET requests and our application doesn't know that they are HEAD requests and thus treats the link as being used.
=> Add pass for chat HEAD request routes

dictionaries.yaml, www/service.tf
The minimum rps for fastly rate limiters is 10, so we will have to use that
=> Set rps limit to 10 for bank-holidays.json rate limiter

www/service.tf, www/www.vcl.tftpl
Trello: https://trello.com/c/evNZhxxc/2285-set-up-410-page-for-govuk-chat-to-be-served-by-govuk
Opened as a draft until I complete the changes to helm charts
GOV.UK Chat is being deintegrated from www.gov.uk now that the private beta has concluded. This removes the additional VCL configuration from Fastly.
=> Remove VCL conditionals for GOV.UK Chat

dictionaries.yaml, www/ab_tests.yaml
This will be used in Finder Frontend to allow us to AB test some config changes in Vertex AI Search.
Initially this has a 5/5/90 split to make sure nothing untoward happens,
we'll dial this up to 50/50/0 shortly.
see https://trello.com/c/7vbzHU0K/774-set-up-ab-test
=> Add `SearchFreshnessBoost` AB test

dictionaries.yaml
This dials the AB test up to 50/50, having successfully verified it at a lower initial split.
=> Start full search freshness boost AB test

dictionaries.yaml, www/ab_tests.yaml
This will allow us to vary traffic between Content Store and GraphQL.
The tests are currently enabled but sending 100% of traffic to Content Store.  We will vary the traffic mix in later PRs.
[Trello card](https://trello.com/c/stxnESVI)
=> Add configuration for GraphQL A/B test

dictionaries.yaml
The dictionaries defining the A/B test percentages were incorrectly named in a3a52acd0173b22cad6ee1650edb312aacd1b609.
Updating them to remove the underscores.
[Trello card](https://trello.com/c/stxnESVI)
=> Fix names for A/B test percentages

dictionaries.yaml
This suspends the test by directing all traffic to `Z`, but keeping the test around as we may be restarting it soon with a different configuration.
=> End `SearchFreshnessBoost` AB test for now

dictionaries.yaml
It receives very little traffic so we're not worried about this :)
=> Bump world index ab to 50%

dictionaries.yaml
This will add the header for the ministers index A/B variant to 1% of all overall traffic, therefore meaning the ministers index page will start receiving a very low amount of traffic.
We will monitor this and increase the traffic level when we are happy the page is performing correctly.
[Trello card](https://trello.com/c/V0SMNIAT)
=> Send 1% of traffic to ministers index A/B test variant

dictionaries.yaml
We are not seeing much traffic at 1% but response time appears to be acceptable, so increasing this to 50% so we can see a considerable increase in traffic.
[Trello card](https://trello.com/c/5ggdXNEB)
=> Increase GraphQL role A/B test to 50%

dictionaries.yaml
We noticed that there are differences for some translated content which we hadn't spotted it before. Rolling back to avoid users seeing different content
=> Rollback the roles A/B test

logs/main.tf, logs/outputs.tf, logs/remote.tf
This outputs the Fastly Logs S3 Bucket ARN so we can pick this up in `govuk-infrastructure` for the new IAM Role that we are switching to.
=> Output Fastly log S3 ARN for use by Infra Repo

logs/main.tf
This changes the Python runtime from 3.8 to 3.13 which Terraform is trying to revert.
=> Fix Lambda Python Runtime Drift

bouncer/service.tf
This is in advance of other services.
As an endpoint for thousands of domains, bouncer is often subject to attacks so this is an easier service to trial than others.
Valid options are `off`, `log`, `block`: https://www.fastly.com/documentation/reference/api/products/ddos_protection/
Setting the mode to block means that traffic from detected attacks will be dropped. It's possible to [override the response to each event](https://manage.fastly.com/security/ddos/protection/events/), or just use the default setting configured for the service (which is what this is)
[Some initial docs](https://github.com/alphagov/govuk-developer-docs/pull/5162) for this have been added
=> Enable DDOS protection blocking mode on bouncer

datagovuk/service.tf, service-domain-redirect/service.tf, tld-redirect/service.tf
Enabling blocking mode for the next tranche of services:
- data.gov.uk
- the redirect for gov.uk --> www.gov.uk
- the redirect for service.gov.uk --> www.gov.uk
I've reviewed the [historical data for past attacks](https://manage.fastly.com/security/ddos/protection/events) back to 30th May, and am confident that no false positives have been registered. I'm happy that we should enable protection on some more services that are not in the critical path.
Similar to https://github.com/alphagov/govuk-fastly/pull/182
=> Enable DDOS blocking on DGU and domain redirects

.github/workflows/actionlint.yml, .github/workflows/build_diff_gen_image.yaml, .github/workflows/ci-terraform.yml
We agree that pinning the versions of GitHub Actions actions to a commit hash
instead of a mutable tag is the correct choice.
We have a lot of places where we use them. The changes in this commit were
generated by using a tool called pinact[1] which can convert pinned tags in GHA
workflows to the commit hash they point to at that moment in time.
To generate the change set I ran `pinact run` from the root of the repository.
[1] https://github.com/suzuki-shunsuke/pinact
=> Globally pin GitHub Actions actions to commit hashes not tags

.github/workflows/ci-terraform.yml
So that it uses the same version as other repositories
=> Update terraform-linters/setup-tflint action

www/www.vcl.tftpl
In the expectation of comms and other publicity which might contain query params
This is only stripped for processing in the CDN and therefore improves our caching capabilities.
=> Strip params to /prepare path

assets/service.tf, tld-redirect/service.tf, www/service.tf
We will be monitoring this, and will flip back if necessary.
It's also possible to manually enable rules from the web interface should this be required.
=> Flip mode in preparation for weekend

assets/service.tf
This partially reverts https://github.com/alphagov/govuk-fastly/pull/197 and allows granular reapplication of blocking mode to the assets services (integration, staging and production).
=> Re-enable blocking on assets

bouncer/bouncer.vcl.tftpl, datagovuk/datagovuk.vcl.tftpl, www/www.vcl.tftpl
Update header styles to match new GOV.UK brand refresh.
=> Update header styles
