- modules/bouncer/bouncer.vcl.tftpl
A change of IP for the office will happen on the first of October. A second PR will follow to remove the old IPs.
> Add new IPs to the office IP range

- ab_tests.yaml
- dictionaries.yaml
https://trello.com/c/jKWA7Nu3/543-ab-test-content-for-find-your-utr-number
> Add FindUtrNumberVideoLinks AB test

- diff-generator/Dockerfile
This fixes blank diffs being generated
> Update nodejs to 18 in diff-generator image

- ab_tests.yaml
- dictionaries.yaml
Trello: https://trello.com/c/GmoMiJii/2289-turn-on-popular-links-ab-test-100-z
Related work: https://github.com/alphagov/frontend/pull/3865
> Add initial setup ready for when we test HomepagePopularLinksTest

- modules/www/service.tf
Despite the name, it used to assume every value was a CIDR netblock (i.e. with a `/nn` prefixlen on the end).
Also some style cleanup while we're in there.
> Accept IP addresses in allowed_ip_addresses.

- dictionaries.yaml
https://trello.com/c/vy77iTj2/2291-update-popular-links-ab-test-25-to-variants
> Extend duration to 7 days for HomepagePopularLinksTest

- modules/assets/service.tf
Same as https://github.com/alphagov/govuk-fastly/pull/41, but I missed the assets config (which is a separate file to the www config).
> Add protocol to athena logs

- dictionaries.yaml
[Trello](https://trello.com/c/XAPAI9sT/212-set-up-ab-test-for-new-search-on-govuk-platform)
Start with 1% of users to make sure everything is working as expected.
> Start vertex search AB test

- ab_tests.yaml
- dictionaries.yaml
Google Vertex AI Search and Conversation is going live as the provider for site search.
> Remove VertexSearch A/B test

- datagovuk.tf
- modules/datagovuk/datagovuk.vcl.tftpl
- modules/datagovuk/service.tf
- modules/datagovuk/variables.tf
Might come in handy for tactical response to DoS etc.
> Fix missing denylist in datagovuk vcl_recv.

- ab_tests.yaml
- dictionaries.yaml
Set up an AB test to compare links in a grid vs. a list
Trello card: https://trello.com/c/l9wMWXrt/2582-setup-newbrowse-ab-test-100-to-z-for-24-hours
> Add AB test for new browse layout

- dictionaries.yaml
https://trello.com/c/jBayG5th/2596-ramp-up-newbrowse-ab-test-50-to-b-for-10-days
> Ramp up NewBrowse AB test to 50%

- modules/datagovuk/datagovuk.vcl.tftpl
This is to allow integration to match logic in PR: https://github.com/alphagov/govuk-fastly/pull/82
> Update to match integration stale content handling

- modules/assets/main.tf
- modules/bouncer/main.tf
- modules/datagovuk/main.tf
- modules/www/main.tf
The allows us to rate limit requests at edge.
> Enable edge rate limiting

- ab_tests.yaml
- dictionaries.yaml
**This is to be merged on Friday 23rd August 2024 11:00am**
[Trello](https://trello.com/c/mcOB0YrA/2748-setup-populartasks-ab-test-100-to-z-for-24-hours-s)
Add the AB test configuration for `PopularTasks` AB test with variants A, B, C and Z.
To prepare for the AB test
> Add PopularTasks AB test

- diff-generator/lambda_function.py
> Fix diff generator not working with new separate workspaces

- diff-generator/lambda_function.py
> Don't attempt to loop through root_module in diff generator

- www/www.vcl.tftpl
> Add missing semi-colon

- README.md
> Update readme to reflect new repo structure

- tld-redirect/service.tf
- tld-redirect/tldredirect.vcl.tftpl
- tld-redirect/variables.tf
This allows us to create tld redirect services for staging and integration.
> Use variable for domain for tld redirects service

- dictionaries.yaml
A 10%
B 10%
Z 80%
https://trello.com/c/DXJTSYhk/3265-scale-to-10-10-80-ab-content-list-test
> Scale up ContentsList AB test

- dictionaries.yaml
A 10%
B 10%
Z 80%
https://trello.com/c/vdMnZ7Ni/3266-scale-to-50-50-0-ab-content-list-test
> Scale up ContentsList AB test 

- dictionaries.yaml
- www/ab_tests.yaml
We will be making a decision on whether we make the content list  a permanent feature if we can validate our hypothesis but this card is to remove the AB test functionality.
[Trello ticket](https://trello.com/c/0VVfVZrA/3273-draft-pr-to-take-down-content-list-ab-test)
> Take down content list AB test

- dictionaries.yaml
- www/ab_tests.yaml
This was missed in a3a52acd0173b22cad6ee1650edb312aacd1b609.
[Trello card](https://trello.com/c/stxnESVI)
> Add World Index to GraphQL A/B test

- dictionaries.yaml
Initial low traffic, will likely be revised.
> Start graphql A/B test

- .github/CODEOWNERS
Relates to https://github.com/alphagov/govuk-platform-internal/issues/61
> Add CODEOWNERS requiring platform engineering review of all changes
